---
title: "Map of capacity and dispatch deltas for certain climate scenarios"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


#setting up globals
```{r cars}
library(tidyverse)
library(lubridate)
library(stringr)
library(RColorBrewer)
library(httr)
library(jsonlite)
library(raster)
library(rgdal)
library(sp)
library(sf)
library(ggrepel)

#reading in load zone shapefiles

#replace file path here:
load_zone_directory <- ""

setwd(load_zone_directory)

#read in data on load zones
load_zones <- read_csv(file="load_zone.csv")

#reading in load zone shapefiles
load_zone_shapes <- st_read(paste(load_zone_directory,"WECC load zones//Load zone shape files//","wecc_load_areas.shp",sep=""))

########################
#set global parameters for reading in SWITCH run results


#MAC

#replace file path here:
switch_input_dir <- ""
#
switch_output_dir <- ""

switch_run_dir <- "SWITCH_WEAP_runs/"

results_dir <- "WEAP_Nov_8_results_SWITCH_Mar_27_results/"

output_folder_name <-"//post-process//"


setwd(switch_input_dir)

#set baseline and climate run names and other globals here:

run_name1 <- "id_202_WECC_0_carbon_baseline_5y_24_sample_barrier"
scenario_name1 <- "Baseline WECC-wide 0 carbon cap"
scenario_name_short1 <- "Baseline no CC"

# climate_impacts_included <- "Hydropower and Water Load Scenarios"
# climate_impacts_included <- "Cooling Load Scenarios"
climate_impacts_included <- "Cooling + Hydropower and Water Load Scenarios"

day <- "Mar_27_"

#color palettes for scenarios and energy sources:

cbpal <- c("#999999","#004949","#009292","#ff6db6","#ffb6db",
           "#490092","#006ddb","#b66dff","#6db6ff","#b6dbff",
           "#920000","#924900","#db6d00","#24ff24","#ffff6d")

cbpal2 <- c("#999999","#004949","#009292","#ff6db6","#ffb6db",
            "#490092","#006ddb","#b66dff","#6db6ff","#b6dbff",
            "#920000","#924900","#db6d00","#24ff24","#ffff6d", "#000000")

energy_source_palette <- c("Oil" = "black", "Biomass" = "springgreen4", "Coal" = "tan4", "Gas" = "#666666","Geothermal" = "#660000","Solar" = "gold","Uranium" = "blueviolet", "Water" = "#0066CC", "Wind" = "deepskyblue1", "Battery Storage" = "aquamarine", "Waste Heat" = "brown", "Curtailment"="red")


#coming up with scenario and run name lists
climate_scenario_list <- c("ACCESS-1.0","bcc-csm1-1","CanESM","CCSM","CESM1-BGC","CESM1-CAM5","CMCC-CM", "CMCC-CMS", "CNRM-CM5","GFDL-CM3", "GFDL-ESM2M" ,"HadGEM2-CC", "HadGEM2-ES","MIROC5", "MPI-ESM-LR"  )

run_name_list <- list(run_name1)
scenario_list <- list(scenario_name1)
short_scenario_list <- list(scenario_name_short1)


for (i in 1:length(climate_scenario_list)){
  
  if (climate_impacts_included == "Hydropower and Water Load Scenarios") {
  new_run_name <- paste(run_name1, climate_scenario_list[i],"Hydro_Load",sep="_")
  run_name_list[[i+1]] <- new_run_name
  
  new_scenario_name <- paste(climate_scenario_list[i], "hydropower, energy for water" ,sep=" ")
  scenario_list[[i+1]] <- new_scenario_name
  
  new_short_scenario_name <- paste(climate_scenario_list[i])
  short_scenario_list[[i+1]] <- new_short_scenario_name
  
   weap_run_dir <- paste(results_dir, "Hydropower and Water Load Scenarios/", sep="")
  
  }else if (climate_impacts_included == "Cooling + Hydropower and Water Load Scenarios"){
    new_run_name <- paste(run_name1, climate_scenario_list[i],"CDD_HDD_Hydro_Load",sep="_")
    run_name_list[[i+1]] <- new_run_name
    
    new_scenario_name <- paste(climate_scenario_list[i], "cooling, hydropower, energy for water" ,sep=" ")
    scenario_list[[i+1]] <- new_scenario_name
    
    new_short_scenario_name <- paste(climate_scenario_list[i])
    short_scenario_list[[i+1]] <- new_short_scenario_name
    
     weap_run_dir <- paste(results_dir, "Cooling + Hydropower and Water Load Scenarios/", sep="")

  }else if  (climate_impacts_included == "Cooling Load Scenarios"){
    new_run_name <- paste(run_name1, climate_scenario_list[i],"CDD_HDD",sep="_")
    run_name_list[[i+1]] <- new_run_name
    
    new_scenario_name <- paste(climate_scenario_list[i], "cooling" ,sep=" ")
    scenario_list[[i+1]] <- new_scenario_name
    
    new_short_scenario_name <- paste(climate_scenario_list[i])
    short_scenario_list[[i+1]] <- new_short_scenario_name
    
    # #PC
    # weap_run_dir <- paste(results_dir, "Cooling Load Scenarios\\", sep="")
    #MAC
    weap_run_dir <- paste(results_dir, "Cooling Load Scenarios/", sep="")
  }
}
```

#Reading in and processing results on generating cap online
```{r Reading in and processing results on generating cap online}
######################
###Generation capacity online####################

gen_cap_source_period_lz <- data.frame()

for (i in 1:length(run_name_list)){
  
  run_name <- run_name_list[[i]]
  scenario <- short_scenario_list[[i]]
  
  #read in the generation capacity builds and generation project information 
  gen_cap <- read.csv(file=paste(switch_input_dir,run_name,"/outputs/","gen_cap.csv",sep=""),stringsAsFactors=F, header = T, fill = TRUE) 
 
  # selecting only the columns of interest
  gen_capacity_cumulative <- subset(gen_cap, select=c(PERIOD, GENERATION_PROJECT, gen_load_zone, gen_tech, gen_energy_source, GenCapacity))
  
  #cleaning the data from possible reading problems ("NA")
  rows <- nrow(gen_capacity_cumulative)
  gen_capacity_cumulative <- na.omit(gen_capacity_cumulative)
  rows2 <- nrow(gen_capacity_cumulative)
  
  #checking how many rows were discarded
  rows-rows2
  
  #specifying CAES gen_tech as CAES gen_energy_source source so it doesn't get lumped into regular gas, and battery storage as gen_energy_source source
  #gen_capacity_cumulative$gen_energy_source[gen_capacity_cumulative$gen_tech == "Compressed_Air_Energy_Storage"] <- "Compressed_Air_Energy_Storage"
  gen_capacity_cumulative$gen_energy_source[gen_capacity_cumulative$gen_tech == "Battery_Storage"] <- "Battery Storage"
  gen_capacity_cumulative$gen_energy_source[gen_capacity_cumulative$gen_energy_source == "Waste_Heat"] <- "Waste Heat"
  
  #also aggregating the bio gen_energy_source categories and renaming oil
  gen_capacity_cumulative$gen_energy_source[gen_capacity_cumulative$gen_energy_source == "Bio_Gas" | gen_capacity_cumulative$gen_energy_source =="Bio_Liquid" | gen_capacity_cumulative$gen_energy_source == "Bio_Solid"] <- "Biomass"
  gen_capacity_cumulative$gen_energy_source[gen_capacity_cumulative$gen_energy_source == "DistillateFuelOil" | gen_capacity_cumulative$gen_energy_source ==  "ResidualFuelOil"] <- "Oil"
  
  #aggregate capacity by generating gen_energy_source souce (across all gen technologies) by load zone and period
  gen_cap_fuelAgg <- gen_capacity_cumulative %>% group_by(gen_load_zone, PERIOD, gen_energy_source) %>% summarize(GenCapacityCumulative_MW = sum(GenCapacity))
  
  #calculating the total cumulative generating capacity by load zone and PERIOD and joining with gen_cap aggregated for each PERIOD by source
  gen_cap_SourceAgg_st <- arrange(gen_cap_fuelAgg, gen_load_zone, PERIOD, gen_energy_source)
  
  gen_cap_PERIOD_total_lz <- gen_cap_SourceAgg_st %>% group_by(gen_load_zone, PERIOD) %>% summarize(Total_Lz_GenCap_MW = sum(GenCapacityCumulative_MW))
  
  gen_cap_SourceAgg_st <- left_join(gen_cap_SourceAgg_st,gen_cap_PERIOD_total_lz,c("gen_load_zone" = "gen_load_zone","PERIOD"="PERIOD"))
  
  gen_cap_SourceAgg_st$Scenario <- scenario
  
  #capacity online by load zone and period for each scenario
  gen_cap_source_period_lz <- rbind(gen_cap_source_period_lz, gen_cap_SourceAgg_st)
  
}

#output csv of capacity installed by load zone by period for each scenario
write.csv(x = gen_cap_source_period_lz, file = paste(switch_output_dir, switch_run_dir, weap_run_dir, day,climate_impacts_included, "LZ_capacity_online.csv",sep=""), row.names = F)

# #total WECC capacity online by period for each scenario
# gen_cap_source_period_WECC <- gen_cap_source_period_lz %>% group_by(Scenario, PERIOD, gen_energy_source) %>% summarize(GenCapacityOnline_MW = sum(GenCapacityCumulative_MW))
# 
# #output csv of total WECC capacity online by period for each scenario
# write.csv(x = gen_cap_source_period_WECC, file = paste(switch_output_dir, switch_run_dir, weap_run_dir, day,climate_impacts_included,"WECCcapacity_online_LONG.csv",sep=""), row.names = F)

#load zone delta between baseline and CC scenarios

baseline <- scenario_name_short1

gen_cap_source_period_lz_baseline <- gen_cap_source_period_lz %>% filter(Scenario == baseline)
gen_cap_source_period_lz_baseline <- rename(gen_cap_source_period_lz_baseline, Baseline_Scenario = Scenario, GenCapacityCumulative_MW_baseline = GenCapacityCumulative_MW, Total_Lz_GenCap_MW_baseline = Total_Lz_GenCap_MW)

gen_cap_source_period_lz_scenario_delta0 <- gen_cap_source_period_lz %>% filter(Scenario != baseline)
gen_cap_source_period_lz_scenario_delta <- left_join(gen_cap_source_period_lz_scenario_delta0, gen_cap_source_period_lz_baseline, c("PERIOD"="PERIOD", "gen_load_zone" = "gen_load_zone","gen_energy_source" = "gen_energy_source"))

gen_cap_source_period_lz_scenario_delta$Delta_GenCapacity_MW <-gen_cap_source_period_lz_scenario_delta$GenCapacityCumulative_MW - gen_cap_source_period_lz_scenario_delta$GenCapacityCumulative_MW_baseline

gen_cap_source_period_lz_scenario_delta$GenCap_perc_change_from_baseline <- round(gen_cap_source_period_lz_scenario_delta$Delta_GenCapacity_MW/gen_cap_source_period_lz_scenario_delta$GenCapacityCumulative_MW_baseline,3)
# 
# #output csv of DELTA load zone capacity online by period for each scenario
# write.csv(x = gen_cap_source_period_lz_scenario_delta, file = paste(switch_output_dir, switch_run_dir, weap_run_dir, day,climate_impacts_included, "DELTA_Lz_capacity_online.csv",sep=""), row.names = F)

# #reading in the delta capacity installed for each period and load zone
# gen_cap_source_period_lz_scenario_delta <- read.csv(file = paste(switch_output_dir, switch_run_dir, weap_run_dir, day, climate_impacts_included, "DELTA_Lz_capacity_online.csv",sep=""),stringsAsFactors=F, header = T)

load_zone_list <- c(unique(gen_cap_source_period_lz_scenario_delta$gen_load_zone))
gen_energy_source_list <-  c(unique(gen_cap_source_period_lz_scenario_delta$gen_energy_source))
period_list <- c(2030, 2035, 2040, 2045, 2050)

full_gen_source_lz_period_list <- crossing(load_zone_list, gen_energy_source_list, period_list)
full_gen_source_lz_period_list <- rename(full_gen_source_lz_period_list, gen_load_zone = load_zone_list, period = period_list, gen_energy_source = gen_energy_source_list)

full_gen_cap_source_period_lz_scenario_delta <- left_join(full_gen_source_lz_period_list, gen_cap_source_period_lz_scenario_delta, c("period"="PERIOD", "gen_load_zone"="gen_load_zone", "gen_energy_source"="gen_energy_source"))

# full_gen_cap_source_period_lz_scenario_delta$Scenario <- scenario
# full_gen_cap_source_period_lz_scenario_delta$Baseline_Scenario <- baseline_scenario_name
```

###Maps of differences in Generation capacity online by energy source, load zone, scenario compared to Baseline
```{r Maps of differences in Generation capacity online by energy source, load zone, scenario compared to Baseline}

#centroid of load zones
library(rgdal)
load_zone_centroid_df <- load_zone_shapes$geometry %>% st_centroid() %>% as.data.frame()

centroid_coords <- as.data.frame(st_coordinates(load_zone_centroid_df$geometry))

#joining centroid coordinates and absolute and percentage differences buildout with load zone shapefiles
centroid_coords2 <- data.frame(load_zone_shapes$LOAD_AREA, centroid_coords)

#Just 2050
gen_2050cap_source_period_lz_scenario_delta <- full_gen_cap_source_period_lz_scenario_delta %>% filter(period == 2050)

gen_2050_online_coord <- left_join(gen_2050cap_source_period_lz_scenario_delta, centroid_coords2, c("gen_load_zone"="load_zone_shapes.LOAD_AREA"))

#join prepared cumulative capacities + centroids with load zone shapes
gen_2050_online_coord_shapes <- left_join(gen_2050_online_coord, load_zone_shapes, c("gen_load_zone"="LOAD_AREA"))
#removing unnecessary columns
gen_2050_online_coord_shapes$PRIMARY_NE <- NULL
gen_2050_online_coord_shapes$PRIMARY_ST <- NULL
gen_2050_online_coord_shapes$ECONOMIC_M <- NULL
gen_2050_online_coord_shapes$RPS_COMPLI <- NULL
gen_2050_online_coord_shapes$RPS_COM_01 <- NULL
gen_2050_online_coord_shapes$SUBSTATION <- NULL
gen_2050_online_coord_shapes$RPS_POLICY <- NULL

#Absolute capacity differences between ACCESS scenario and Baseline scenario

gen_energy_source_list <- list("Wind","Solar","Battery Storage")

sc <- scale_fill_gradient2 (name = "Delta Capacity (GW)", low = "blue", mid = "white", high = "red" ,  na.value = "grey", limits=c(-15, 15), )

scenario <- "ACCESS-1.0"

library(cowplot)

#FIGURE 5B
#Vertical version
plot_file_name <- paste("Fig5b_Vertical_map_","solar_wind_bat","_2050_Delta_capacity", ".png", sep="")

png(paste(switch_output_dir, switch_run_dir, weap_run_dir, plot_file_name, sep=""), width=800, height=800, res=100)
plot1 <- ggplot() +
  geom_sf(data = subset(gen_2050_online_coord_shapes, gen_energy_source == gen_energy_source_list[[1]]), aes(group = gen_load_zone, geometry = geometry, fill = Delta_GenCapacity_MW/1000)) +
  sc + 
  coord_sf() +
  ggtitle(paste(gen_energy_source_list[[1]], sep=" ")) +
  theme(panel.grid.major = element_line(color="white"), panel.grid.minor = element_line(color="white"), axis.line = element_blank(), axis.text = element_blank(), axis.title = element_blank() , panel.border = element_blank(), panel.background = element_blank(), axis.ticks = element_blank(), plot.title = element_text(hjust = 0.2, size=12), legend.text = element_text(size=14), legend.title = element_text(size = 16), legend.position = "none", legend.spacing.y = unit(0.01, "cm"), plot.margin = unit(c(0, 0, 0, 0), "cm")) +
  geom_path(color="black") 

plot2 <- ggplot() +
  geom_sf(data = subset(gen_2050_online_coord_shapes, gen_energy_source == gen_energy_source_list[[2]]), aes(group = gen_load_zone, geometry = geometry, fill = Delta_GenCapacity_MW/1000)) +
  sc + 
  coord_sf() +
  ggtitle(paste(gen_energy_source_list[[2]], sep=" ")) +
  theme(panel.grid.major = element_line(color="white"), panel.grid.minor = element_line(color="white"), axis.line = element_blank(), axis.text = element_blank(), axis.title = element_blank() , panel.border = element_blank(), panel.background = element_blank(), axis.ticks = element_blank(), plot.title = element_text(hjust = 0.2, size=12), legend.text = element_text(size=14), legend.title = element_text(size = 16), legend.position = "none", legend.spacing.y = unit(0.01, "cm") ,plot.margin = unit(c(0, 0, 0, 0), "cm")) +
  geom_path(color="black") 
plot3 <- ggplot() +
  geom_sf(data = subset(gen_2050_online_coord_shapes, gen_energy_source == gen_energy_source_list[[3]]), aes(group = gen_load_zone, geometry = geometry, fill = Delta_GenCapacity_MW/1000)) +
  sc + 
  coord_sf() +
  ggtitle(paste(gen_energy_source_list[[3]], sep=" ")) +
  theme(panel.grid.major = element_line(color="white"), panel.grid.minor = element_line(color="white"), axis.line = element_blank(), axis.text = element_blank(), axis.title = element_blank() , panel.border = element_blank(), panel.background = element_blank(), axis.ticks = element_blank(), plot.title = element_text(hjust = 0.2, size=12), legend.text = element_text(size=10), legend.title = element_text(size = 10), legend.position = "bottom", legend.spacing.x = unit(0.04, "cm"), plot.margin = unit(c(0, 0, 0, 0), "cm"))  +
  geom_path(color="black") 

plot_grid(plot1, plot2, plot3, ncol = 1, rel_heights=c(0.8,0.8, 1))


dev.off()
```

####Map of Baseline generating capacity buildout and Tx buildout
```{r ####Map of Baseline generating capacity buildout and Tx buildout}

library(scatterpie)
library(RColorBrewer)

#read in the transmission capacity builds and transmission project information for baseline scenario (run1)

build_tx <- read.csv(file=paste(switch_input_dir,run_name1,"/outputs/","transmission.csv",sep=""),stringsAsFactors=F, header = T, fill = TRUE) 

#parsing out the start and end of transmission lines
library(plyr)
#joining parsed line names to build capacity
tx_lines <- ldply(str_split(build_tx$TRANSMISSION_LINE,"-",n=3))
colnames(tx_lines) <- c("Load_zone1","Load_zone2")
build_tx <- cbind(build_tx, tx_lines)
#making list of line pairs
tx_lines2 <- as.data.frame(build_tx$TRANSMISSION_LINE)
tx_lines2$tx_line_pair <- as.character(tx_lines2$`build_tx$TRANSMISSION_LINE`)
tx_lines_list <- list(tx_lines2$tx_line_pair)

detach(package:plyr)
library(dplyr)

cummulative_buildtx <- build_tx %>% rename(cumulative_BuildTx_MW = TxCapacityNameplate)

#join centroids with load zone number

#read in the load zone names and ids information

load_zone_ids <- read.csv(file=paste(switch_input_dir,run_name1,"/inputs/","load_zones.csv",sep=""),stringsAsFactors=F, header = T, fill = TRUE) 

#joining centroid coordinates by Name with load zone id (the index of the transmission buildout)
centroid_coords3 <- left_join(centroid_coords2, load_zone_ids, c("load_zone_shapes.LOAD_AREA" = "LOAD_ZONE"))

centroid_coords3 <- centroid_coords3 %>% rename(LOAD_ZONE = load_zone_shapes.LOAD_AREA, LOAD_ZONE_ID = zone_dbid)

centroid_coords3$zone_ccs_distance_km <- NULL

#join transmission capacity with load zone centroid info (for each load zone at the start and end of the transmission line)
cummulative_buildtx$Load_zone1 <- as.integer(cummulative_buildtx$Load_zone1)
cummulative_buildtx$Load_zone2 <- as.integer(cummulative_buildtx$Load_zone2)

cummulative_buildtx_merged1 <- left_join(cummulative_buildtx, centroid_coords3, c('Load_zone1'='LOAD_ZONE_ID'))

cummulative_buildtx_merged1 <- cummulative_buildtx_merged1 %>% rename(LOAD_ZONE1 = LOAD_ZONE, X1 = X, Y1=Y)

cummulative_buildtx_merged2 <- left_join(cummulative_buildtx_merged1, centroid_coords3, c('Load_zone2'='LOAD_ZONE_ID'))

cummulative_buildtx_merged2 <- cummulative_buildtx_merged2 %>% rename(LOAD_ZONE2 = LOAD_ZONE, X2 = X, Y2=Y)

cummulative_buildtx_merged2$cumulative_BuildTx_GW <- cummulative_buildtx_merged2$cumulative_BuildTx_MW/1000
cummulative_buildtx_merged2$existing_trans_cap_GW <- cummulative_buildtx_merged2$existing_trans_cap/1000
cummulative_buildtx_merged2$BuildTx_GW <- ifelse(is.na(as.numeric(cummulative_buildtx_merged2$BuildTx)/1000)==TRUE, 0 ,as.numeric(cummulative_buildtx_merged2$BuildTx)/1000)


cummulative_buildtx_merged2 <- cummulative_buildtx_merged2 %>% group_by(TRANSMISSION_LINE, trans_lz1, trans_lz2, Load_zone1, Load_zone2, LOAD_ZONE1, LOAD_ZONE2) %>% mutate(cumulative_newBuildTx_GW = sum(BuildTx_GW)) %>% ungroup()


cummulative_buildtx_merged2_long <- gather(cummulative_buildtx_merged2, Tx_type, Tx_GW, cumulative_BuildTx_GW, existing_trans_cap_GW)
cummulative_buildtx_merged2_long$Tx_type <- ifelse(cummulative_buildtx_merged2_long$Tx_type == "cumulative_BuildTx_GW", "New Tx Capacity Built", "Existing Tx Capacity")
#filtering out Canadian and Mexican load zones
# cummulative_buildtx_merged2_US <-cummulative_buildtx_merged2 %>% filter(LOAD_ZONE1 != "CAN_ALB" & LOAD_ZONE1 !="CAN_BC" & LOAD_ZONE2 != "CAN_ALB" & LOAD_ZONE2 !="CAN_BC" & LOAD_ZONE1 !="MEX_BAJA" & LOAD_ZONE2 != "MEX_BAJA")
# 
# cummulative_buildtx_merged2_US$cumulative_BuildTx_GW <- cummulative_buildtx_merged2_US$cumulative_BuildTx_MW/1000

baseline_gen_2050_coord_shapes <- gen_2050_online_coord_shapes %>% filter(Scenario == "ACCESS-1.0")
baseline_gen_2050_coord_shapes_wide <- spread(baseline_gen_2050_coord_shapes, gen_energy_source, GenCapacityCumulative_MW_baseline, fill = NA)
baseline_gen_2050_coord_shapes_wide$GenCapacityCumulative_MW <- NULL
baseline_gen_2050_coord_shapes_wide$Scenario <- NULL
baseline_gen_2050_coord_shapes_wide$Total_Lz_GenCap_MW <- NULL
baseline_gen_2050_coord_shapes_wide$Delta_GenCapacity_MW <- NULL
baseline_gen_2050_coord_shapes_wide$GenCap_perc_change_from_baseline <- NULL

baseline_gen_2050_coord_shapes_wide <- baseline_gen_2050_coord_shapes_wide %>% group_by(period, gen_load_zone, Total_Lz_GenCap_MW_baseline, X, Y, geometry) %>% summarize(Battery_Storage=sum(`Battery Storage`,na.rm=TRUE), Biomass = sum(Biomass ,na.rm=TRUE), Coal = sum(Coal,na.rm=TRUE), Gas = sum(Gas,na.rm=TRUE), Geothermal=sum(Geothermal,na.rm=TRUE),  Solar=sum(Solar,na.rm=TRUE),  Uranium=sum(Uranium,na.rm=TRUE), Water=sum(Water,na.rm=TRUE), Wind=sum(Wind,na.rm=TRUE), `Waste Heat` = sum(`Waste Heat`, na.rm = TRUE))


#calculating the radius, based on the total capacity buildout across all sources
baseline_gen_2050_coord_shapes_wide$radius <- sqrt(baseline_gen_2050_coord_shapes_wide$Total_Lz_GenCap_MW_baseline/pi)

#FIGURE 5A

#scatterpie with generation pie chargs and transmission buildout in line segments

period_list <- c(2050)

period <- 2050
plot_file_name <- paste("Fig5A_map_",period,"Baseline_WECC_Gen_Tx_cap", sep="")

png(paste(switch_output_dir, switch_run_dir, weap_run_dir, plot_file_name, sep=""), width=900, height=900, res=100)

Build_Gen_Tx <-
  ggplot() +
  geom_polygon(fill="white") + geom_path(color="black") + #filling in and outlining load zones
  geom_sf(data = baseline_gen_2050_coord_shapes_wide, aes(group = gen_load_zone, geometry = geometry)) + #subsetting the gen capacity buildout for the particular year
  ggtitle("2050 Generation & Tx Capacity Online Baseline Scenario") +
  geom_segment(data=subset(cummulative_buildtx_merged2_long, PERIOD == period), aes(x = X1, y = Y1, xend = X2, yend = Y2, linewidth = Tx_GW, color=Tx_type)) +
  # scale_linewidth("Tx Capacity (GW)", guide = "legend")  + #transmission buildout lines
  scale_linewidth("Tx Capacity (GW)", guide = "legend", limits=c(0.01,25))  + #transmission buildout lines
  scale_color_manual(name = "Tx type", guide = "legend",  values =  c("pink", "red"),
                    breaks = c("Existing Tx Capacity", "New Tx Capacity Built"), labels = c("Existing Tx Capacity", "New Tx Capacity Built")) +
  geom_scatterpie(aes(x = X, y = Y, r = radius/100), data = baseline_gen_2050_coord_shapes_wide, cols= c("Biomass", "Coal","Gas","Geothermal","Battery_Storage","Solar","Uranium","Water","Wind","Waste Heat"), color="#666666")  + 
  scale_fill_manual(name="Energy Source", values = c( "Biomass" = "springgreen4", "Coal" = "tan4", "Gas" = "#666666","Geothermal" = "#660000","Solar" = "gold","Uranium" = "blueviolet", "Water" = "#0066CC", "Wind" = "deepskyblue1", "Battery_Storage" = "aquamarine", "Waste Heat" = "brown")) +  #scatterpie of gen cap mix by source
  geom_text() + annotate("text", x=-125,y=33.5,label="Gen Capacity (GW)",size=4) + #title for pie chart legend
  geom_scatterpie_legend(radius=baseline_gen_2050_coord_shapes_wide$radius/100, x=-125, y=30, n=4, labeller = function(x) round(((x*100)^2)*pi/1000,-1)) + #lengend for pie chart size
  theme(panel.grid.major = element_line(color="white"), panel.grid.minor = element_line(color="white"), axis.line = element_blank(), 
        axis.text = element_blank(), axis.title = element_blank() , panel.border = element_blank(), panel.background = element_blank(), axis.ticks = element_blank(), 
        plot.title = element_text(hjust = 0.2, size=16), legend.text = element_text(size=10), legend.title = element_text(size = 12), legend.position = "bottom", 
        legend.spacing.y = unit(0.01, "cm"), legend.direction = "horizontal", legend.box = "vertical") +
  guides(fill=guide_legend(nrow=3, order = 1), linewidth = guide_legend(order = 3),col = guide_legend(order = 2))

print(Build_Gen_Tx)

dev.off()
  
```

#MAP of Temperature and load coefficients
```{r map of temperature and load coefficients}

#centroid of load zones
library(rgdal)
load_zone_centroid_df <- load_zone_shapes$geometry %>% st_centroid() %>% as.data.frame()

centroid_coords <- as.data.frame(st_coordinates(load_zone_centroid_df$geometry))

#joining centroid coordinates and absolute and percentage differences buildout with load zone shapefiles
centroid_coords2 <- data.frame(load_zone_shapes$LOAD_AREA, centroid_coords)

#Read in the total net load change per degree day change  2050
lz_heat_cool_slopes2050 <- read.csv(file = '/switch_lz_2050_avg_cc_cool_heat_slopes.csv', header = T,stringsAsFactors=F )

lz_heat_cool_slopes2050_coord <- left_join(lz_heat_cool_slopes2050, centroid_coords2, c("load_zone_name"="load_zone_shapes.LOAD_AREA"))

#join prepared cumulative capacities + centroids with load zone shapes
lz_heat_cool_slopes2050_coordshapes <- left_join(lz_heat_cool_slopes2050_coord, load_zone_shapes, c("load_zone_name"="LOAD_AREA"))
#removing unnecessary columns
lz_heat_cool_slopes2050_coordshapes$PRIMARY_NE <- NULL
lz_heat_cool_slopes2050_coordshapes$PRIMARY_ST <- NULL
lz_heat_cool_slopes2050_coordshapes$ECONOMIC_M <- NULL
lz_heat_cool_slopes2050_coordshapes$RPS_COMPLI <- NULL
lz_heat_cool_slopes2050_coordshapes$RPS_COM_01 <- NULL
lz_heat_cool_slopes2050_coordshapes$SUBSTATION <- NULL
lz_heat_cool_slopes2050_coordshapes$RPS_POLICY <- NULL

library(RColorBrewer)


#FIGURE 1
library(cowplot)
plot_file_name <- paste("Fig1_lz_map_","CDD_slope_2050", ".png", sep="")

png(paste(switch_output_dir, switch_run_dir, weap_run_dir, plot_file_name, sep=""), width=1200, height=600, res=100)
  
plot1 <- ggplot() +
  geom_sf(data = subset(lz_heat_cool_slopes2050_coordshapes, type_degree_days == "CDD" & load_zone_name !="CAN_BC" & load_zone_name != "CAN_ALB" & load_zone_name !="MEX_BAJA"), aes(group = load_zone_name, geometry = geometry, fill = avg_switch_response_mw_delta_dd)) +
  coord_sf() +
  scale_fill_gradient(low = "white", high = "red", name="MW/change in CDD") +
  ggtitle("Average 2050 load response per change in CDD") +
  theme(panel.grid.major = element_line(color="white"), panel.grid.minor = element_line(color="white"), axis.line = element_blank(), axis.text = element_blank(), axis.title = element_blank() , panel.border = element_blank(), panel.background = element_blank(), axis.ticks = element_blank(), plot.title = element_text(hjust = 0.2, size=14), legend.text = element_text(size=10), legend.title = element_text(size = 10), legend.position = "right", legend.spacing.x = unit(0.01, "cm"), plot.margin = unit(c(0, 0, 0, 0), "cm")) +
  geom_path(color="black") 

plot2 <- ggplot() +
  geom_sf(data = subset(lz_heat_cool_slopes2050_coordshapes, type_degree_days == "HDD" & load_zone_name !="CAN_BC" & load_zone_name != "CAN_ALB" & load_zone_name !="MEX_BAJA"), aes(group = load_zone_name, geometry = geometry, fill = avg_switch_response_mw_delta_dd)) +
  coord_sf() +
  scale_fill_gradient(low = "white", high = "#0066FF", name="MW/change in HDD") +
  ggtitle("Average 2050 load response per change in HDD") +
  theme(panel.grid.major = element_line(color="white"), panel.grid.minor = element_line(color="white"), axis.line = element_blank(), axis.text = element_blank(), axis.title = element_blank() , panel.border = element_blank(), panel.background = element_blank(), axis.ticks = element_blank(), plot.title = element_text(hjust = 0.2, size=14), legend.text = element_text(size=10), legend.title = element_text(size = 10), legend.position = "right", legend.spacing.x = unit(0.01, "cm"), plot.margin = unit(c(0, 0, 0, 0), "cm")) +
  geom_path(color="black") 

plot_grid(plot1, plot2, ncol = 2, rel_heights=c(1, 1))

dev.off()

#FIGURE 1
##plot of just SWITCH load zones
load_zone_shapes_centroids <- left_join(load_zone_shapes, centroid_coords2, c("LOAD_AREA"="load_zone_shapes.LOAD_AREA"))

plot_file_name <- paste("Fig1_WECC_SWITCH_lz_map", ".png", sep="")

png(paste(switch_output_dir, switch_run_dir, weap_run_dir, plot_file_name, sep=""), width=1200, height=600, res=100)

ggplot() +
  geom_sf(data = load_zone_shapes_centroids, aes(group = LOAD_AREA, geometry = geometry)) +
  #geom_text(data = load_zone_shapes_centroids, aes(x=X, y=Y, label = LOAD_AREA) ) +
  coord_sf() +
  ggtitle("SWITCH WECC Load Zones") +
  theme(panel.grid.major = element_line(color="white"), panel.grid.minor = element_line(color="white"), axis.line = element_blank(), axis.text = element_blank(), axis.title = element_blank() , panel.border = element_blank(), panel.background = element_blank(), axis.ticks = element_blank(), plot.title = element_text(hjust = 0.2, size=14), legend.text = element_text(size=10), legend.title = element_text(size = 10), legend.position = "none", legend.spacing.x = unit(0.01, "cm"), plot.margin = unit(c(0, 0, 0, 0), "cm")) +
  geom_path(color="black") 

dev.off()

#SUPPLEMENTARY FIGURE 5

plot_file_name <- paste("SI_labeled_WECC_SWITCH_lz_map", ".png", sep="")

png(paste(switch_output_dir, switch_run_dir, weap_run_dir, plot_file_name, sep=""), width=1200, height=600, res=100)

ggplot() +
  geom_sf(data = load_zone_shapes_centroids, aes(group = LOAD_AREA, geometry = geometry)) +
  # geom_sf_label(data = load_zone_shapes_centroids, aes(label = LOAD_AREA)) +   
  geom_text(data = load_zone_shapes_centroids, aes(x=X, y=Y, label = LOAD_AREA), size=2 ) +
  coord_sf() +
  ggtitle("SWITCH WECC Load Zones") +
  theme(panel.grid.major = element_line(color="white"), panel.grid.minor = element_line(color="white"), axis.line = element_blank(), axis.text = element_blank(), axis.title = element_blank() , panel.border = element_blank(), panel.background = element_blank(), axis.ticks = element_blank(), plot.title = element_text(hjust = 0.2, size=14), legend.text = element_text(size=10), legend.title = element_text(size = 10), legend.position = "none", legend.spacing.x = unit(0.01, "cm"), plot.margin = unit(c(0, 0, 0, 0), "cm")) +
  geom_path(color="black") 

dev.off()
```


